# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6983f047478d70815765f7007c344c5b6f0816bb4a91c4c2ca8379d28254c2483dcc456ddb38bcabedfa655ba1475f7897f101d7bef38281937d3c5035046289

test:
  secret_key_base: ab6cc4bb98a46bc0ef71fce09f6c651b490808a2ad1a72ec9231e6af2609c4c2efd0bba75e4ac6db982de3d4a6b6731f34ea2d76dda6ece39a8dd0785f2adb71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
